Vesrion: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "master"
    labels:
      - "Dependabot"
    assignees:
      - "abhishek24236"
